### ISSUE TITLE
Categories not working

### ISSUE THREAD

**Issue by vachanda** [netresearch/docker-entermediadb#1]
Hi,

I used `netresearch/entermediadb:latest` docker image to run entermedia. There are a couple of issues with the entermedia application :

1) The categories module is not present at all. 
![screen shot 2016-11-11 at 2 27 36 pm](https://cloud.githubusercontent.com/assets/12047814/20209566/08567940-a81b-11e6-9bc0-80ce817f9212.png)

The docker logs report this error -

```
[Unlimitedpool-1-thread-1] ERROR org.entermediadb.events.PathEvent -
org.openedit.OpenEditException: /WEB-INF/base/entermedia/catalog/_site.xconf#MediaArchiveModule.getMediaArchive no such index
	at org.openedit.ModuleManager.execMethod(ModuleManager.java:119)
	at org.openedit.ModuleManager.executePageAction(ModuleManager.java:61)
	at org.openedit.ModuleManager.executePathActions(ModuleManager.java:184)
	at org.openedit.servlet.BaseOpenEditEngine.executePathActions(BaseOpenEditEngine.java:232)
	at org.entermediadb.events.PathEvent.runNow(PathEvent.java:339)
	at org.entermediadb.events.PathEvent.execute(PathEvent.java:285)
	at org.entermediadb.events.TaskRunner.executeNow(TaskRunner.java:233)
	at org.entermediadb.events.TaskRunner.runBlocking(TaskRunner.java:179)
	at org.entermediadb.events.TaskRunner$1.run(TaskRunner.java:155)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [assets_catalog] IndexNotFoundException[no such index]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:151)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:95)
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteSingleIndex(IndexNameExpressionResolver.java:208)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.<init>(TransportSingleShardAction.java:138)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.<init>(TransportSingleShardAction.java:115)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.doExecute(TransportSingleShardAction.java:87)
	at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.doExecute(TransportSingleShardAction.java:51)
	at org.elasticsearch.action.support.TransportAction.doExecute(TransportAction.java:149)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:137)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
	at org.entermediadb.elasticsearch.searchers.BaseElasticSearcher.searchByField(BaseElasticSearcher.java:1656)
	at org.openedit.data.BaseSearcher.searchById(BaseSearcher.java:2039)
	at org.entermediadb.elasticsearch.searchers.ElasticListSearcher.searchById(ElasticListSearcher.java:206)
	at org.openedit.data.SearcherManager.getData(SearcherManager.java:338)
	at org.entermediadb.asset.MediaArchive.getCatalogSetting(MediaArchive.java:1317)
	at org.entermediadb.asset.MediaArchive.getCatalogSettingValue(MediaArchive.java:1332)
	at org.entermediadb.asset.MediaArchive.getMediaDbId(MediaArchive.java:344)
	at org.entermediadb.asset.modules.BaseMediaModule.getMediaArchive(BaseMediaModule.java:91)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openedit.ModuleManager.execMethod(ModuleManager.java:107)
	... 11 more
```

2) Not able to add groups or roles to the library privacy settings.

Is this related to the overrides you are adding?

**Comment by copitz** [comment]
I don't think so but I don't actually know - maybe its related to [this](https://github.com/entermedia-community/app-emshare/issues/7)?

If you find a solution, I'd love to add it to this repo - thank you.

**Comment by vachanda** [comment]
I tried the suggestion in the above mentioned link. That just helps to display the categories manually created. The automatic category creation upon upload from website or from hot folder is not working.
